env:
  browser: true
  es2021: true
extends:
  - "plugin:vue/vue3-essential"
  # - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  -  "@vue/prettier"
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
rules: {}