name: auto_test
on: push
env:
  MYSQL_ROOT_PASSWORD: password
  RAILS_ENV: test
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_HOST: 127.0.0.1
  MYSQL_PORT: 3306
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Prepare Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
          ruby-version: '3.0.0'
          bundler-cache: true
     
      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: yarn
        run: yarn --frozen-lockfile

  build-test:
    name: auto build-test
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
      - name: Check Ruby version
        run: ruby -v

      - name: Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: yarn
        run: yarn --frozen-lockfile

      - name: Bundle install
        run: bundle install

      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load
      # Run Linter
      - name: run Prettier and ESLint
        run: |
          yarn run fmt
          yarn run rbfmt
      - name: Run Breakman
        run: |
          bundle exec brakeman -q -w2
      # - name: Run Rubocop
      #   run: |
      #     bundle exec rubocop -A